booking_requests = [
	{id: 1,
	 name: 'Name 1 last name 1',
	 email: 'maiv@gmail.com',
	 event_date: Time.now,
	 budget: 13000,
	 company: 'Cantosombrio company',
	 phone: '123456789',
	 event_location: 'California',
	 comments: 'Algun comentario',
	 service_id: 1,
	 celebrity_id: 1,
	 site: Site.first
	},
	{id: 2,
	 name: 'Name 2 last name 2',
	 email: 'Argus@gmail.com',
	 event_date: Time.now,
	 budget: 13000,
	 company: 'Titanes company',
	 phone: '123456789',
	 event_location: 'California',
	 comments: 'Algun comentario',
	 service_id: 3,
	 celebrity_id: 2,
	 site: Site.first
	},
	{id: 3,
	 name: 'Name 3 last name 3',
	 email: 'sylvanas@gmail.com',
	 event_date: Time.now,
	 budget: 13000,
	 company: 'Susurraviento company',
	 phone: '123456789',
	 event_location: 'California',
	 comments: 'Algun comentario',
	 service_id: 2,
	 celebrity_id: 1,
	 site: Site.first
	},
	{id: 4,
	 name: 'Name 4 last name 4',
	 email: 'tyrande@gmail.com',
	 event_date: Time.now,
	 budget: 13000,
	 company: 'Susurraviento company',
	 phone: '967813456',
	 event_location: 'California',
	 comments: 'Algun comentario',
	 service_id: 6,
	 site: Site.first
	}
]

BookingRequest.create!(booking_requests)
