default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  
development:
  <<: *default
  database: hirecelebrity_development

test:
  <<: *default
  database: hirecelebrity_test

production:
  <<: *default
  database: <%= ENV['HIRECELEBRITY_DATABASE'] %>
  username: <%= ENV['HIRECELEBRITY_DATABASE_USERNAME'] %>
  password: <%= ENV['HIRECELEBRITY_DATABASE_PASSWORD'] %>
  host: <%= ENV['HIRECELEBRITY_DATABASE_HOSTNAME'] %>
  port: <%= ENV['HIRECELEBRITY_DATABASE_PORT'] %>

